### ISSUE TITLE
Support backends from salt mine

### ISSUE THREAD

**Issue by mchugh19** [saltstack-formulas/haproxy-formula#44]
It would be great if this could support getting backend information from the salt mine. 

Here's a quick partial solution that I worked up for my own needs. Adding the key `servers_from_mine` it will add backends from `mine.get 'value' network.ip_addrs`. It's only a partial solution as this does not handle specifying port, check, or extra as in the pillar version.

```
  backends:
    backend1:
      name: www-backend
      balance: roundrobin
      redirects:
        - scheme https if !{ ssl_fc }
      servers_from_mine: 'web*'
```

```
diff --git a/haproxy/templates/haproxy.jinja b/haproxy/templates/haproxy.jinja
index ed0a689..9584ebf 100644
--- a/haproxy/templates/haproxy.jinja
+++ b/haproxy/templates/haproxy.jinja
@@ -500,10 +500,17 @@ backend {{ backend.get('name', backend_name) }}
     {%- if 'defaultserver' in backend %}
     default-server {%- for option, value in backend.defaultserver|dictsort %} {{ ' '.join((option, value|string, '')) }} {%- endfor %}
     {%- endif %}
-    {%- if 'servers' in backend %}
-      {%- for server_name, server in backend.servers|dictsort %}
-    server {{ server.get('name', server_name) }} {{ server.host }}{% if 'port' in server %}:{{ server.port }}{% endif %} {{ server.get('check', '') }} {{ server.get('extra', '') }}
+    {%- if 'servers_from_mine' in backend %}
+      {%- set matcher = backend.servers_from_mine %}
+      {%- for server, addrs in salt['mine.get'](matcher, 'network.ip_addrs').items() %}
+      server {{ server }} {{ addrs[0] }}:80 check
       {%- endfor %}
+    {%- else %}
+      {%- if 'servers' in backend %}
+        {%- for server_name, server in backend.servers|dictsort %}
+      server {{ server.get('name', server_name) }} {{ server.host }}{% if 'port' in server %}:{{ server.port }}{% endif %} {{ server.get('check', '') }} {{ server.get('extra', '') }}
+        {%- endfor %}
+      {%- endif %}
     {%- endif %}
   {% endfor %}
 {%- endif %}
```

**Comment by johnkeates** [comment]
Wouldn't this work with inline JINJA in the pillar as well?

**Comment by mchugh19** [comment]
@johnkeates You blew my mind with that suggestion! Looks like this wasn't possible until newer than 2015.8.3. But after updating to 2015.8.7, and reading over saltstack/salt#11509 I was able to get this going from the pillar itself

```
  backends:
    backend1:
      name: www-backend
      balance: roundrobin
      servers:
        {% for server, addrs in salt['saltutil.runner']('mine.get', tgt='web*', fun='network.ip_addrs').items() %}
        {{ server }}:
          name: {{ server }}
          host: {{ addrs[0] }}
          port: 80
          check: check
        {% endfor %}
```

While sort of nuts, that does handle my use case and can close this out.
