### ISSUE TITLE
Adding support for crt-list

### ISSUE THREAD

**Issue by fintanmm** [saltstack-formulas/haproxy-formula#62]
Hi all,

Would it be possible to add support for crt-lists as a state for haproxy. Maybe something like this.

```YAML
/etc/haproxy/cert-list.txt:
  file.managed:
    - source: salt://haproxy/files/cert-list.txt
    - user: haproxy
    - group: haproxy
    - mode: 640
    - template: jinja
    - defaults:
        certlist: {{ salt['pillar.get']('haproxy:certlist') }}
```
and the template file would look something like this
```Jinja2
{% for domain, cert_location in certlist.iteritems() %}
{{ cert_location }} {{ domain }}
{% endfor %}

Thanks
Fintan

**Comment by fintanmm** [comment]
The pillar data could look like this.

```YAML
  certlist:
    www.example*: /etc/haproxy/certs/www.example.com.pem
    *.acme.com: /etc/haproxy/certs/acme.com.pem
```
