### ISSUE TITLE
support for `server-template`

### ISSUE THREAD

**Issue by geoffjukes** [saltstack-formulas/haproxy-formula#88]
Hi,

I'd like to add a `server-template` to the `backend` config to support service discovery from Consul.

It works if I edit the config manually, but if I add it to the Pillar, the formula just ignores it.

Example:

```
haproxy:
  frontends:
    my_frontend:
      bind:
      - "*:8080"
      default_backend: my_backend

  backends:
    my_backend:
      balance: roundrobin
      server-template: my_backend 1 _service-name._tcp.service.consul resolvers consul resolve-prefer ipv4 check

  resolvers:
    consul:
      options:
      - nameserver consul 127.0.0.1:8600
      - accepted_payload_size 8192
      - hold valid 5s
```

should render as:

```
#------------------
# DNS resolvers
#------------------
resolvers consul
    nameserver consul 127.0.0.1:8600
    accepted_payload_size 8192
    hold valid 5s

#------------------
# frontend instances
#------------------
frontend my_frontend
    bind        *:8080
    default_backend my_backend



#------------------
# backend instances
#------------------
backend my_backend
    balance roundrobin
    server-template service-name 1 _service-name._tcp.service.consul resolvers consul resolve-prefer ipv4 check
```

Many thanks,

Geoff

**Comment by geoffjukes** [comment]
After posting this ticket and looking at the template, I discovered the `extra` option. This works for my purposes, and I hope this ticket helps someone.

```
  backends:
    my_backend:
      balance: roundrobin
      extra:
      - server-template my_backend 1 _service-name._tcp.service.consul resolvers consul resolve-prefer ipv4 check
```
